### PR TITLE
popstate gets called on initial page load in some browsers (https://code...

### PR DESCRIPTION
**Pull request by austinhallock**
....google.com/p/chromium/issues/detail?id=63040)

this ignores any popstate before an initial route

### CODE REVIEW

**Comment by Zolmeister** [comment]
tests

**Comment by austinhallock** [comment]
https://github.com/Zorium/zorium/commit/11437210fe4dcb351e16628bbf7b63905e37e677

**Comment by Zolmeister** [comment]
rebase

**Comment by austinhallock** [comment]
done

**Comment by Zolmeister** [comment]
v0.6.8

**Pull request merged**
